### PR TITLE
Update metadata versions

### PR DESCRIPTION
**Pull request by pillarsdotnet**
Apparently it is not possible for the tests to pass.

### CODE REVIEW

**Comment by jarpy** [comment]
This look good, thanks!

I don't know what's wrong with Travis, but the changes in your first commit pass just fine when I run the tests locally. If you'd be kind enough to change this PR back to just your initial commit, I'll gladly merge it.

Cheers.

**Comment by pillarsdotnet** [comment]
Done.

**Comment by pillarsdotnet** [comment]
@jarpy Still awaiting merge.

**Comment by jarpy** [comment]
Thanks! I'll cut a new release for this now.

**Comment by pillarsdotnet** [comment]
Thanks, @jarpy 

While you're at it, I have related PR's (with similar unrelated failures) awaiting review:
* https://github.com/elastic/puppet-logstash/pull/391
* https://github.com/elastic/puppet-elasticsearch/pull/1044

**Comment by jarpy** [comment]
Released in [6.3.2](https://forge.puppet.com/elastic/elastic_stack/6.3.2/readme).

**Pull request merged**
